<#
.SYNOPSIS
    Quantize BF16/F16/F32 GGUF models to ROCmFP4 / ROCmFPX with straight vs agent preset selection on Windows.

.DESCRIPTION
    Native PowerShell implementation of quantize-rocmfpx-agent.sh for Windows environments.
    Translates format and agent profiles into corresponding GGML ROCmFP presets.

.PARAMETER Src
    Path to input BF16/F16/F32 GGUF file.

.PARAMETER Out
    Path for output GGUF file or shard prefix.

.PARAMETER Format
    Target format: rocmfp3 | rocmfp4 | rocmfp6 | rocmfp8 | rocmi4 (default: rocmfp4).

.PARAMETER Profile
    Target profile: straight | agent | fast | fast-coherent | strix | strix-lean | lean | agent-lean (default: agent).

.PARAMETER Preset
    Explicit preset name override (e.g. Q4_0_ROCMFP4_COHERENT, Q3_0_ROCMFPX_AGENT).

.PARAMETER KeepSplit
    Preserve input shard count if source is split.

.PARAMETER DryRun
    Show command and print estimated output size without writing file.

.PARAMETER NThreads
    Optional thread count for llama-quantize.

.PARAMETER Imatrix
    Optional path to importance matrix file generated by llama-imatrix.

.PARAMETER TensorTypeFile
    Optional tensor override file for experimental policies.

.PARAMETER QuantizeBin
    Path to llama-quantize.exe binary. Auto-discovered if omitted.

.EXAMPLE
    .\scripts\quantize-rocmfpx-agent.ps1 -Src model-f16.gguf -Out model-fp4.gguf -Format rocmfp4 -Profile agent

.EXAMPLE
    $env:SRC="model-f16.gguf"; $env:OUT="model-fp4-fast.gguf"; .\scripts\quantize-rocmfpx-agent.ps1 -Profile fast
#>

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [Alias("Source", "InputFile")]
    [string]$Src = $env:SRC,

    [Parameter(Position = 1)]
    [Alias("Output", "OutputFile")]
    [string]$Out = $env:OUT,

    [Parameter()]
    [ValidateSet("rocmfp3", "rocmfp4", "rocmfp6", "rocmfp8", "rocmi4")]
    [string]$Format = $(if ($env:FORMAT) { $env:FORMAT } else { "rocmfp4" }),

    [Parameter()]
    [ValidateSet("straight", "agent", "fast", "fast-coherent", "fast_coherent", "strix", "strix-lean", "strix_lean", "lean", "agent-lean", "agent_lean")]
    [string]$Profile = $(if ($env:PROFILE) { $env:PROFILE } else { "agent" }),

    [Parameter()]
    [string]$Preset = $env:PRESET,

    [Parameter()]
    [switch]$KeepSplit = ($env:KEEP_SPLIT -eq "1"),

    [Parameter()]
    [switch]$DryRun = ($env:DRY_RUN -eq "1"),

    [Parameter()]
    [int]$NThreads = $(if ($env:NTHREADS) { [int]$env:NTHREADS } else { 0 }),

    [Parameter()]
    [string]$Imatrix = $env:IMATRIX,

    [Parameter()]
    [string]$TensorTypeFile = $env:TENSOR_TYPE_FILE,

    [Parameter()]
    [string]$QuantizeBin = $env:QUANTIZE_BIN
)

$ErrorActionPreference = "Stop"

# Enable unified memory by default for ROCm to avoid VRAM allocation failures
if (-not $env:GGML_HIP_ENABLE_UNIFIED_MEMORY) {
    $env:GGML_HIP_ENABLE_UNIFIED_MEMORY = "1"
}

# Auto-discover llama-quantize.exe
if (-not $QuantizeBin) {
    $candidates = @(
        "$PSScriptRoot\..\build\bin\llama-quantize.exe",
        "$PSScriptRoot\..\build\bin\Release\llama-quantize.exe",
        "$PSScriptRoot\..\build-strix-rocmfp4\bin\llama-quantize.exe",
        "$PSScriptRoot\..\build\bin\llama-quantize"
    )
    foreach ($cand in $candidates) {
        if (Test-Path $cand) {
            $QuantizeBin = (Resolve-Path $cand).Path
            break
        }
    }
    if (-not $QuantizeBin) {
        $cmd = Get-Command "llama-quantize.exe" -ErrorAction SilentlyContinue
        if ($cmd) {
            $QuantizeBin = $cmd.Source
        }
    }
}

if (-not $Src -or -not $Out) {
    Write-Error "Both -Src (input GGUF) and -Out (output GGUF) are required."
    exit 2
}

if (-not $QuantizeBin -or -not (Test-Path $QuantizeBin)) {
    Write-Error "Could not find llama-quantize binary. Build it with .\build.ps1 or specify -QuantizeBin."
    exit 1
}

if (-not (Test-Path $Src)) {
    Write-Error "Source file does not exist: $Src"
    exit 1
}

if ($Imatrix -and -not (Test-Path $Imatrix)) {
    Write-Error "Imatrix file does not exist: $Imatrix"
    exit 1
}

if ($TensorTypeFile -and -not (Test-Path $TensorTypeFile)) {
    Write-Error "Tensor type file does not exist: $TensorTypeFile"
    exit 1
}

# Resolve preset if not explicitly overridden
if (-not $Preset) {
    $pair = "$Format`:$Profile"
    switch -Regex ($pair) {
        "rocmfp3:straight"       { $Preset = "Q3_0_ROCMFPX" }
        "rocmfp3:agent"          { $Preset = "Q3_0_ROCMFPX_AGENT" }
        "rocmfp4:straight"       { $Preset = "Q4_0_ROCMFP4" }
        "rocmfp4:agent"          { $Preset = "Q4_0_ROCMFP4_COHERENT" }
        "rocmfp4:fast"           { $Preset = "Q4_0_ROCMFP4_FAST" }
        "rocmfp4:fast[-_]coherent" { $Preset = "Q4_0_ROCMFP4_FAST_COHERENT" }
        "rocmfp4:strix$"         { $Preset = "Q4_0_ROCMFP4_STRIX" }
        "rocmfp4:strix[-_]lean"  { $Preset = "Q4_0_ROCMFP4_STRIX_LEAN" }
        "rocmfp6:straight"       { $Preset = "Q6_0_ROCMFPX" }
        "rocmfp6:agent$"         { $Preset = "Q6_0_ROCMFPX_AGENT" }
        "rocmfp6:lean$"          { $Preset = "Q6_0_ROCMFPX_LEAN" }
        "rocmfp6:agent[-_]lean"  { $Preset = "Q6_0_ROCMFPX_AGENT_LEAN" }
        "rocmfp8:straight"       { $Preset = "Q8_0_ROCMFPX" }
        "rocmfp8:agent"          { $Preset = "Q8_0_ROCMFPX_AGENT" }
        "rocmi4:.*"              { $Preset = "Q4_0_ROCMI4" }
        default {
            Write-Error "Unsupported Format/Profile combination: Format=$Format, Profile=$Profile"
            exit 2
        }
    }
}

$quantArgs = @()
if ($KeepSplit) {
    $quantArgs += "--keep-split"
}
if ($DryRun) {
    $quantArgs += "--dry-run"
}
if ($Imatrix) {
    $quantArgs += @("--imatrix", $Imatrix)
}
if ($TensorTypeFile) {
    $quantArgs += @("--tensor-type-file", $TensorTypeFile)
}

$quantArgs += @($Src, $Out, $Preset)
if ($NThreads -gt 0) {
    $quantArgs += $NThreads.ToString()
}

$outDir = [System.IO.Path]::GetDirectoryName($Out)
if ($outDir -and -not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

Write-Host "================ ROCmFPX Quantization ================" -ForegroundColor Cyan
Write-Host "Source:           $Src"
Write-Host "Output:           $Out"
Write-Host "Format:           $Format"
Write-Host "Profile:          $Profile"
Write-Host "Preset:           $Preset"
Write-Host "Split:            $KeepSplit"
if ($Imatrix)        { Write-Host "Imatrix:          $Imatrix" }
if ($TensorTypeFile) { Write-Host "TensorTypeFile:   $TensorTypeFile" }
Write-Host "Quantize Binary:  $QuantizeBin"
Write-Host "======================================================" -ForegroundColor Cyan

if ($DryRun) {
    Write-Host "[DRY RUN] Executing dry run check..." -ForegroundColor Yellow
}

& $QuantizeBin @quantArgs
if ($LASTEXITCODE -ne 0) {
    Write-Error "llama-quantize exited with error code $LASTEXITCODE"
    exit $LASTEXITCODE
}

if (-not $DryRun) {
    $stem = [System.IO.Path]::GetFileNameWithoutExtension($Out)
    $ext = [System.IO.Path]::GetExtension($Out)
    $searchDir = if ($outDir) { $outDir } else { "." }
    $shardPattern = "$stem-*-of-*$ext"
    $shards = Get-ChildItem -Path $searchDir -Filter $shardPattern -ErrorAction SilentlyContinue

    $fileList = @()
    if ($shards -and $shards.Count -gt 0) {
        foreach ($f in $shards) {
            $fileList += [PSCustomObject]@{
                Path = $f.FullName
                Bytes = $f.Length
            }
        }
    } elseif (Test-Path $Out) {
        $f = Get-Item $Out
        $fileList += [PSCustomObject]@{
            Path = $f.FullName
            Bytes = $f.Length
        }
    }

    $summary = [PSCustomObject]@{
        Status          = "pass"
        Source          = $Src
        Output          = $Out
        Format          = $Format
        Profile         = $Profile
        Preset          = $Preset
        Imatrix         = if ($Imatrix) { $Imatrix } else { $null }
        TensorTypeFile  = if ($TensorTypeFile) { $TensorTypeFile } else { $null }
        Files           = $fileList
    }

    $json = $summary | ConvertTo-Json -Depth 4
    Write-Output $json
}
